### ISSUE TITLE
Cannot set height and width

### ISSUE THREAD

**Issue by iexplore** [DoubleTrade/custom-scrollbar#1]
I tried to use this very nice component in app-layout components but it doesn't get a height and width if I use 100%. The only way to make it work is to move the --custom-scrollbar-height on the host and a new --custom-scrollbar-width on div.scrollbar.
I am no CSS layout crack so it there might be another solution.

**Comment by RoXuS** [comment]
Hello @iexplore,

Can you past an example of your code in order to test if we have a bug or a better solution ?

Thx !

**Comment by iexplore** [comment]
Hello @RoXuS ,

Thx for you quick response!
The div is stretching from the toolbar to the bottom of the browser.

HTML
```
<dom-module id="ew-lesson">
  <template>
    <style  include="lesson-style"></style>

    <app-route route="{{route}}" pattern="/:lessonId" data="{{routeData}}" tail="{{subroute}}"></app-route>
    <app-route route="{{subroute}}" pattern="/page/:pageNo" data="{{subrouteData}}"></app-route>
    <app-drawer-layout id="drawerLayout" fullbleed responsive-width="1040px">
      <!-- Drawer Pane -->
      <app-drawer id="drawerPanel" slot="drawer">
        <app-header id="drawerHeader" fixed shadow class="toc">
          <app-toolbar id="tocToolbar">
            <div id="tocToolbarTitle">[[lessonType]]</div> <!-- t("toc") -->
            <a href="/to-courses/last" alt$="[[t('goto_course_overview')]]" title$="[[t('goto_course_overview')]]">
              <!-- <paper-icon-button icon="icons:folder"></paper-icon-button> -->
            </a>
            <!-- <paper-icon-button icon="close" on-tap="toggleToc" ></paper-icon-button> -->
          </app-toolbar>
        </app-header>
        <!-- TOC menu -->
        <custom-scrollbar id="tocscroll" class="simple">
          <paper-material id="papertoc" elevation="2">
            <ew-toc id="toc" class="list" on-iron-activate="_listTap" selected-page-no="{{pageNo}}"
                    max-jump-page="{{maxJumpPage}}" table-of-contents="{{tableOfContents}}"></ew-toc>
            <p>&nbsp;</p>
          </paper-material>
        </custom-scrollbar>
    </app-drawer>

```
CSS
```
      custom-scrollbar.simple {
        --custom-scrollbar-height: 100%;
        --custom-scrollbar-width: 100%;
        --custom-scrollbar-bar: {
          background: red;
        }

```
Change in custom-scrollbar.html
```
       :host {
        height: var(--custom-scrollbar-height, 200px); 
        .....
      }

      .scrollbar {
        width: var(--custom-scrollbar-width, 200px); 
        ....
      }

```

**Comment by iexplore** [comment]
Oeps; Just played around with it and it didn't work (probably caching earlier).
It worked after I gave both the :host and div.scrollbar the height setting.

Sorry for the inconvenience.

**Comment by RoXuS** [comment]
@iexplore ah ok ! But you set the height of the scrollbar in my component ?

**Comment by iexplore** [comment]
@RoXuS First is tried it live during debugging to see what would work.
for further testing I set the height and width in your component (because you cannot change it any other way in shadow dom)
```
:host {
        height: var(--custom-scrollbar-height, 200px); 
        .....
      }

.scrollbar {
        width: var(--custom-scrollbar-width, 200px); 
        height: var(--custom-scrollbar-height, 200px); 
       ....
      }
```
And then of course the CSS settings in my code to activate and that did the trick
```
      custom-scrollbar.simple {
        --custom-scrollbar-height: 100%;
        --custom-scrollbar-width: 100%;
        --custom-scrollbar-bar: {
          background: red;
        }
```

**Comment by iexplore** [comment]
@RoXuS I have implemented to scroll-bar in our application with a CSS expert and it works without changes.
I mistakenly thought  that you could only style an element with css variables, but the element itself can of course be targeted normally.  Sorry for that.  

Thanks for you work!
